[package]
name = "simd_alphatensor_rs"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
    "codegen",
]

[dev-dependencies]
criterion = "0.3"
ndarray = "0.15.6"

[[bench]]
name = "my_benchmark"
harness = false